package com.club.web.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hm_home_information
 */
public class HmHomeInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.id
     *
     * @FieldComment 主键id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.title
     *
     * @FieldComment Title
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.urlpath
     *
     * @FieldComment 存储路径
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String urlpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.sorting
     *
     * @FieldComment 排序
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer sorting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.status
     *
     * @FieldComment 启用 1.启用,0.关闭
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.create_time
     *
     * @FieldComment 创建时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.update_time
     *
     * @FieldComment 更新时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.admin_id
     *
     * @FieldComment 操作人id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_home_information.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.id
     *
     * @FieldComment 主键id
     *
     * @return the value of hm_home_information.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.id
     *
     * @FieldComment 主键id
     *
     * @param id the value for hm_home_information.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.title
     *
     * @FieldComment Title
     *
     * @return the value of hm_home_information.title
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.title
     *
     * @FieldComment Title
     *
     * @param title the value for hm_home_information.title
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.urlpath
     *
     * @FieldComment 存储路径
     *
     * @return the value of hm_home_information.urlpath
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getUrlpath() {
        return urlpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.urlpath
     *
     * @FieldComment 存储路径
     *
     * @param urlpath the value for hm_home_information.urlpath
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setUrlpath(String urlpath) {
        this.urlpath = urlpath == null ? null : urlpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.sorting
     *
     * @FieldComment 排序
     *
     * @return the value of hm_home_information.sorting
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getSorting() {
        return sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.sorting
     *
     * @FieldComment 排序
     *
     * @param sorting the value for hm_home_information.sorting
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setSorting(Integer sorting) {
        this.sorting = sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.status
     *
     * @FieldComment 启用 1.启用,0.关闭
     *
     * @return the value of hm_home_information.status
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.status
     *
     * @FieldComment 启用 1.启用,0.关闭
     *
     * @param status the value for hm_home_information.status
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.create_time
     *
     * @FieldComment 创建时间
     *
     * @return the value of hm_home_information.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.create_time
     *
     * @FieldComment 创建时间
     *
     * @param createTime the value for hm_home_information.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.update_time
     *
     * @FieldComment 更新时间
     *
     * @return the value of hm_home_information.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.update_time
     *
     * @FieldComment 更新时间
     *
     * @param updateTime the value for hm_home_information.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @return the value of hm_home_information.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @param isDelete the value for hm_home_information.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.admin_id
     *
     * @FieldComment 操作人id
     *
     * @return the value of hm_home_information.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.admin_id
     *
     * @FieldComment 操作人id
     *
     * @param adminId the value for hm_home_information.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_home_information.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @return the value of hm_home_information.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_home_information.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @param adminName the value for hm_home_information.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}