package com.club.web.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_authority
 */
public class SysAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.id
     *
     * @FieldComment 
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.aut_name
     *
     * @FieldComment 权限(模块)名称
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String autName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.aut_note
     *
     * @FieldComment 权限备注
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String autNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.aut_url
     *
     * @FieldComment 权限地址
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String autUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.status
     *
     * @FieldComment 状态 1.启用,0.停用
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.create_time
     *
     * @FieldComment 创建时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.update_time
     *
     * @FieldComment 更新时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.admin_id
     *
     * @FieldComment 操作人id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.id
     *
     * @FieldComment 
     *
     * @return the value of sys_authority.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.id
     *
     * @FieldComment 
     *
     * @param id the value for sys_authority.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.aut_name
     *
     * @FieldComment 权限(模块)名称
     *
     * @return the value of sys_authority.aut_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getAutName() {
        return autName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.aut_name
     *
     * @FieldComment 权限(模块)名称
     *
     * @param autName the value for sys_authority.aut_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAutName(String autName) {
        this.autName = autName == null ? null : autName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.aut_note
     *
     * @FieldComment 权限备注
     *
     * @return the value of sys_authority.aut_note
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getAutNote() {
        return autNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.aut_note
     *
     * @FieldComment 权限备注
     *
     * @param autNote the value for sys_authority.aut_note
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAutNote(String autNote) {
        this.autNote = autNote == null ? null : autNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.aut_url
     *
     * @FieldComment 权限地址
     *
     * @return the value of sys_authority.aut_url
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getAutUrl() {
        return autUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.aut_url
     *
     * @FieldComment 权限地址
     *
     * @param autUrl the value for sys_authority.aut_url
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAutUrl(String autUrl) {
        this.autUrl = autUrl == null ? null : autUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.status
     *
     * @FieldComment 状态 1.启用,0.停用
     *
     * @return the value of sys_authority.status
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.status
     *
     * @FieldComment 状态 1.启用,0.停用
     *
     * @param status the value for sys_authority.status
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.create_time
     *
     * @FieldComment 创建时间
     *
     * @return the value of sys_authority.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.create_time
     *
     * @FieldComment 创建时间
     *
     * @param createTime the value for sys_authority.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.update_time
     *
     * @FieldComment 更新时间
     *
     * @return the value of sys_authority.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.update_time
     *
     * @FieldComment 更新时间
     *
     * @param updateTime the value for sys_authority.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @return the value of sys_authority.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @param isDelete the value for sys_authority.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.admin_id
     *
     * @FieldComment 操作人id
     *
     * @return the value of sys_authority.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.admin_id
     *
     * @FieldComment 操作人id
     *
     * @param adminId the value for sys_authority.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @return the value of sys_authority.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @param adminName the value for sys_authority.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}