package com.club.web.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_news_type
 */
public class SysNewsType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.id
     *
     * @FieldComment 主键
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.type_name
     *
     * @FieldComment 新闻类别名称
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.type_context
     *
     * @FieldComment 新闻类别介绍
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String typeContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.is_delete
     *
     * @FieldComment 是否删除 1.正常 0.删除
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.create_time
     *
     * @FieldComment 创建时间
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.update_time
     *
     * @FieldComment 更新时间
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.admin_id
     *
     * @FieldComment 操作人id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_type.admin_name
     *
     * @FieldComment 操作人
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.id
     *
     * @FieldComment 主键
     *
     * @return the value of sys_news_type.id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.id
     *
     * @FieldComment 主键
     *
     * @param id the value for sys_news_type.id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.type_name
     *
     * @FieldComment 新闻类别名称
     *
     * @return the value of sys_news_type.type_name
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.type_name
     *
     * @FieldComment 新闻类别名称
     *
     * @param typeName the value for sys_news_type.type_name
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.type_context
     *
     * @FieldComment 新闻类别介绍
     *
     * @return the value of sys_news_type.type_context
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getTypeContext() {
        return typeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.type_context
     *
     * @FieldComment 新闻类别介绍
     *
     * @param typeContext the value for sys_news_type.type_context
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setTypeContext(String typeContext) {
        this.typeContext = typeContext == null ? null : typeContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.is_delete
     *
     * @FieldComment 是否删除 1.正常 0.删除
     *
     * @return the value of sys_news_type.is_delete
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.is_delete
     *
     * @FieldComment 是否删除 1.正常 0.删除
     *
     * @param isDelete the value for sys_news_type.is_delete
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.create_time
     *
     * @FieldComment 创建时间
     *
     * @return the value of sys_news_type.create_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.create_time
     *
     * @FieldComment 创建时间
     *
     * @param createTime the value for sys_news_type.create_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.update_time
     *
     * @FieldComment 更新时间
     *
     * @return the value of sys_news_type.update_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.update_time
     *
     * @FieldComment 更新时间
     *
     * @param updateTime the value for sys_news_type.update_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.admin_id
     *
     * @FieldComment 操作人id
     *
     * @return the value of sys_news_type.admin_id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.admin_id
     *
     * @FieldComment 操作人id
     *
     * @param adminId the value for sys_news_type.admin_id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_type.admin_name
     *
     * @FieldComment 操作人
     *
     * @return the value of sys_news_type.admin_name
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_type.admin_name
     *
     * @FieldComment 操作人
     *
     * @param adminName the value for sys_news_type.admin_name
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}