package com.club.web.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_news_context
 */
public class SysNewsContext {
	
	private String typeName;
	
	
    public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.id
     *
     * @FieldComment 主键
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.title
     *
     * @FieldComment 新闻标题
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.context
     *
     * @FieldComment 新闻内容
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.label
     *
     * @FieldComment 新闻标签 热词
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.type_id
     *
     * @FieldComment 新闻类别外键
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.is_delete
     *
     * @FieldComment 是否删除 1.正常 0.删除
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.create_time
     *
     * @FieldComment 创建时间
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.update_time
     *
     * @FieldComment 更新时间
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.admin_id
     *
     * @FieldComment 操作人id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news_context.admin_name
     *
     * @FieldComment 操作人
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.id
     *
     * @FieldComment 主键
     *
     * @return the value of sys_news_context.id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.id
     *
     * @FieldComment 主键
     *
     * @param id the value for sys_news_context.id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.title
     *
     * @FieldComment 新闻标题
     *
     * @return the value of sys_news_context.title
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.title
     *
     * @FieldComment 新闻标题
     *
     * @param title the value for sys_news_context.title
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.context
     *
     * @FieldComment 新闻内容
     *
     * @return the value of sys_news_context.context
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.context
     *
     * @FieldComment 新闻内容
     *
     * @param context the value for sys_news_context.context
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.label
     *
     * @FieldComment 新闻标签 热词
     *
     * @return the value of sys_news_context.label
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.label
     *
     * @FieldComment 新闻标签 热词
     *
     * @param label the value for sys_news_context.label
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.type_id
     *
     * @FieldComment 新闻类别外键
     *
     * @return the value of sys_news_context.type_id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.type_id
     *
     * @FieldComment 新闻类别外键
     *
     * @param typeId the value for sys_news_context.type_id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.is_delete
     *
     * @FieldComment 是否删除 1.正常 0.删除
     *
     * @return the value of sys_news_context.is_delete
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.is_delete
     *
     * @FieldComment 是否删除 1.正常 0.删除
     *
     * @param isDelete the value for sys_news_context.is_delete
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.create_time
     *
     * @FieldComment 创建时间
     *
     * @return the value of sys_news_context.create_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.create_time
     *
     * @FieldComment 创建时间
     *
     * @param createTime the value for sys_news_context.create_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.update_time
     *
     * @FieldComment 更新时间
     *
     * @return the value of sys_news_context.update_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.update_time
     *
     * @FieldComment 更新时间
     *
     * @param updateTime the value for sys_news_context.update_time
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.admin_id
     *
     * @FieldComment 操作人id
     *
     * @return the value of sys_news_context.admin_id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.admin_id
     *
     * @FieldComment 操作人id
     *
     * @param adminId the value for sys_news_context.admin_id
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news_context.admin_name
     *
     * @FieldComment 操作人
     *
     * @return the value of sys_news_context.admin_name
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news_context.admin_name
     *
     * @FieldComment 操作人
     *
     * @param adminName the value for sys_news_context.admin_name
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}