package com.club.web.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role
 */
public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @FieldComment 主键id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @FieldComment 角色名称
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_note
     *
     * @FieldComment 权限备注
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String roleNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.status
     *
     * @FieldComment 是否启用 1.启用,0禁用
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_time
     *
     * @FieldComment 创建时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.update_time
     *
     * @FieldComment 更新时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.is_delete
     *
     * @FieldComment 
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.admin_id
     *
     * @FieldComment 操作人id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @FieldComment 主键id
     *
     * @return the value of sys_role.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @FieldComment 主键id
     *
     * @param id the value for sys_role.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @FieldComment 角色名称
     *
     * @return the value of sys_role.role_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @FieldComment 角色名称
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_note
     *
     * @FieldComment 权限备注
     *
     * @return the value of sys_role.role_note
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getRoleNote() {
        return roleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_note
     *
     * @FieldComment 权限备注
     *
     * @param roleNote the value for sys_role.role_note
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setRoleNote(String roleNote) {
        this.roleNote = roleNote == null ? null : roleNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.status
     *
     * @FieldComment 是否启用 1.启用,0禁用
     *
     * @return the value of sys_role.status
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.status
     *
     * @FieldComment 是否启用 1.启用,0禁用
     *
     * @param status the value for sys_role.status
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_time
     *
     * @FieldComment 创建时间
     *
     * @return the value of sys_role.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_time
     *
     * @FieldComment 创建时间
     *
     * @param createTime the value for sys_role.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.update_time
     *
     * @FieldComment 更新时间
     *
     * @return the value of sys_role.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.update_time
     *
     * @FieldComment 更新时间
     *
     * @param updateTime the value for sys_role.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.is_delete
     *
     * @FieldComment 
     *
     * @return the value of sys_role.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.is_delete
     *
     * @FieldComment 
     *
     * @param isDelete the value for sys_role.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.admin_id
     *
     * @FieldComment 操作人id
     *
     * @return the value of sys_role.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.admin_id
     *
     * @FieldComment 操作人id
     *
     * @param adminId the value for sys_role.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @return the value of sys_role.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @param adminName the value for sys_role.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}