package com.club.web.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_aut
 */
public class SysRoleAut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_aut.id
     *
     * @FieldComment 主键id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_aut.role_id
     *
     * @FieldComment 角色id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_aut.aut_id
     *
     * @FieldComment 权限id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer autId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_aut.create_time
     *
     * @FieldComment 创建时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_aut.update_time
     *
     * @FieldComment 更新时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_aut.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_aut.id
     *
     * @FieldComment 主键id
     *
     * @return the value of sys_role_aut.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_aut.id
     *
     * @FieldComment 主键id
     *
     * @param id the value for sys_role_aut.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_aut.role_id
     *
     * @FieldComment 角色id
     *
     * @return the value of sys_role_aut.role_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_aut.role_id
     *
     * @FieldComment 角色id
     *
     * @param roleId the value for sys_role_aut.role_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_aut.aut_id
     *
     * @FieldComment 权限id
     *
     * @return the value of sys_role_aut.aut_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getAutId() {
        return autId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_aut.aut_id
     *
     * @FieldComment 权限id
     *
     * @param autId the value for sys_role_aut.aut_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAutId(Integer autId) {
        this.autId = autId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_aut.create_time
     *
     * @FieldComment 创建时间
     *
     * @return the value of sys_role_aut.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_aut.create_time
     *
     * @FieldComment 创建时间
     *
     * @param createTime the value for sys_role_aut.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_aut.update_time
     *
     * @FieldComment 更新时间
     *
     * @return the value of sys_role_aut.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_aut.update_time
     *
     * @FieldComment 更新时间
     *
     * @param updateTime the value for sys_role_aut.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_aut.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @return the value of sys_role_aut.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_aut.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @param isDelete the value for sys_role_aut.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}