package com.club.web.model;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_version_update_record
 */
public class SysVersionUpdateRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.id
     *
     * @FieldComment 主键id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.theme
     *
     * @FieldComment 主题
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.update_details
     *
     * @FieldComment 更新详情
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String updateDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.new_version
     *
     * @FieldComment 新版本
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String newVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.original_version
     *
     * @FieldComment 原版本
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String originalVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.important_updates
     *
     * @FieldComment 是否属于重要更新 1.是,0.否
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String importantUpdates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.epoch_version
     *
     * @FieldComment 更新所属纪元版本
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String epochVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.create_time
     *
     * @FieldComment 创建时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.update_time
     *
     * @FieldComment 更新时间
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.admin_id
     *
     * @FieldComment 操作人id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_version_update_record.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    private String adminName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.id
     *
     * @FieldComment 主键id
     *
     * @return the value of sys_version_update_record.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.id
     *
     * @FieldComment 主键id
     *
     * @param id the value for sys_version_update_record.id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.theme
     *
     * @FieldComment 主题
     *
     * @return the value of sys_version_update_record.theme
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.theme
     *
     * @FieldComment 主题
     *
     * @param theme the value for sys_version_update_record.theme
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.update_details
     *
     * @FieldComment 更新详情
     *
     * @return the value of sys_version_update_record.update_details
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getUpdateDetails() {
        return updateDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.update_details
     *
     * @FieldComment 更新详情
     *
     * @param updateDetails the value for sys_version_update_record.update_details
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setUpdateDetails(String updateDetails) {
        this.updateDetails = updateDetails == null ? null : updateDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.new_version
     *
     * @FieldComment 新版本
     *
     * @return the value of sys_version_update_record.new_version
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getNewVersion() {
        return newVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.new_version
     *
     * @FieldComment 新版本
     *
     * @param newVersion the value for sys_version_update_record.new_version
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setNewVersion(String newVersion) {
        this.newVersion = newVersion == null ? null : newVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.original_version
     *
     * @FieldComment 原版本
     *
     * @return the value of sys_version_update_record.original_version
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getOriginalVersion() {
        return originalVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.original_version
     *
     * @FieldComment 原版本
     *
     * @param originalVersion the value for sys_version_update_record.original_version
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setOriginalVersion(String originalVersion) {
        this.originalVersion = originalVersion == null ? null : originalVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.important_updates
     *
     * @FieldComment 是否属于重要更新 1.是,0.否
     *
     * @return the value of sys_version_update_record.important_updates
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getImportantUpdates() {
        return importantUpdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.important_updates
     *
     * @FieldComment 是否属于重要更新 1.是,0.否
     *
     * @param importantUpdates the value for sys_version_update_record.important_updates
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setImportantUpdates(String importantUpdates) {
        this.importantUpdates = importantUpdates == null ? null : importantUpdates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.epoch_version
     *
     * @FieldComment 更新所属纪元版本
     *
     * @return the value of sys_version_update_record.epoch_version
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getEpochVersion() {
        return epochVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.epoch_version
     *
     * @FieldComment 更新所属纪元版本
     *
     * @param epochVersion the value for sys_version_update_record.epoch_version
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setEpochVersion(String epochVersion) {
        this.epochVersion = epochVersion == null ? null : epochVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.create_time
     *
     * @FieldComment 创建时间
     *
     * @return the value of sys_version_update_record.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.create_time
     *
     * @FieldComment 创建时间
     *
     * @param createTime the value for sys_version_update_record.create_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.update_time
     *
     * @FieldComment 更新时间
     *
     * @return the value of sys_version_update_record.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.update_time
     *
     * @FieldComment 更新时间
     *
     * @param updateTime the value for sys_version_update_record.update_time
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @return the value of sys_version_update_record.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.is_delete
     *
     * @FieldComment 是否删除 1.正常,0.删除
     *
     * @param isDelete the value for sys_version_update_record.is_delete
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.admin_id
     *
     * @FieldComment 操作人id
     *
     * @return the value of sys_version_update_record.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.admin_id
     *
     * @FieldComment 操作人id
     *
     * @param adminId the value for sys_version_update_record.admin_id
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_version_update_record.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @return the value of sys_version_update_record.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_version_update_record.admin_name
     *
     * @FieldComment 操作人姓名
     *
     * @param adminName the value for sys_version_update_record.admin_name
     *
     * @mbggenerated Wed Aug 09 10:05:14 CST 2017
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }
}