package com.club.web.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.club.web.model.SysNewsType;

public class SysNewsTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news_type
     * @param record  Model for table sys_news_type
     * @return   The combine SQL for table sys_news_type
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String insertSelective(SysNewsType record) {
        BEGIN();
        INSERT_INTO("sys_news_type");
        
        if (record.getTypeName() != null) {
            VALUES("type_name", "#{typeName,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeContext() != null) {
            VALUES("type_context", "#{typeContext,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            VALUES("is_delete", "#{isDelete,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAdminId() != null) {
            VALUES("admin_id", "#{adminId,jdbcType=INTEGER}");
        }
        
        if (record.getAdminName() != null) {
            VALUES("admin_name", "#{adminName,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news_type
     * @param record  Model for table sys_news_type
     * @return   The combine SQL for table sys_news_type
     *
     * @mbggenerated Wed Sep 27 14:25:26 CST 2017
     */
    public String updateByPrimaryKeySelective(SysNewsType record) {
        BEGIN();
        UPDATE("sys_news_type");
        
        if (record.getTypeName() != null) {
            SET("type_name = #{typeName,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeContext() != null) {
            SET("type_context = #{typeContext,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDelete() != null) {
            SET("is_delete = #{isDelete,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAdminId() != null) {
            SET("admin_id = #{adminId,jdbcType=INTEGER}");
        }
        
        if (record.getAdminName() != null) {
            SET("admin_name = #{adminName,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}